### ISSUE TITLE
decoder.q not found 

### ISSUE THREAD

**Issue by guruvasuraj** [AquaQAnalytics/TorQ-CME#3]
The command 
q torq.q -load decoder.q -proctype decoder -procname decoder -files sample/sample_20170101.log -debug -tallbook

results in 'decoder.q. OS reports: No such file or directory

Where's the decode.q file located? I am not able to find it in both the repositories. Could you please help me with that?

Thanks,
Guru.

**Comment by tsmyth-aquaq** [comment]
It looks like that example command from the `README` refers to a path that may have existed historically for `decoder.q` as the process seems to have been renamed to `cmedecoder` since then. Can you try the following command instead and let us know if it is successful?
```
q torq.q -load code/processes/cmedecoder.q -proctype cmedecoder -procname cmedecoder -files sample/sample_20170101.log -debug -tallbook
```
